### ISSUE TITLE
Wrong API Key

### ISSUE THREAD

**Issue by reynoldwu** [Isilon/isilon_stat_browser#1]
Most of the API keys are wrong in the document, when "key" are misused as "keys". Please update all of them. 

Example1 
Current: 
https://xxx:8080/platform/1/statistics/current?**keys**=node.audit.cee.export.rate

Correct: 
https://xxxx:8080/platform/1/statistics/current?**key**=node.audit.cee.export.rate

Example2
Current:
https://xxxx:8080/platform/1/statistics/current?keys=cluster.protostats.nfs.total
Correct:
https://xxxx:8080/platform/1/statistics/current?key=cluster.protostats.nfs.total

**Comment by apecoraro** [comment]
We should probably update the README.md to be specific about the version of OneFS that this tool supports. The 'keys' parameter was added to the /platform/1/statistics/current end point in OneFS 8.0. Although, I think it is a bug that the version number in the end point URL did not change between OneFS 7.2 and OneFS 8.0.

**Comment by cbrainerd** [comment]
Resolved by PR #6
