### ISSUE TITLE
Create the tag file failed.

### ISSUE THREAD

**Issue by higkoo** [Isilon/isilon_stat_browser#7]
### create tag file error
> ./build_stat_browser.py --cluster isilon.higkoo.com
> Cluster username: root
> Password:******* 
> 2016-05-25T17:11:00 [ERROR] Unable to open /opt/isilon_stat_browser/stat_key_browser/data/key_tags.json: [Errno 2] No such file or directory: '/opt/isilon_stat_browser/stat_key_browser/data/key_tags.json'
> 2016-05-25T17:11:00 [ERROR] Try running 'make tags' to create the tag file

#### Client
> Linux higkoo 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u2 (2016-01-02) x86_64 GNU/Linux
> Python 2.7.9

#### OneFS
> Isilon OneFS shd-isilon-1 v7.2.1.1 Isilon OneFS v7.2.1.1 B_7_2_1_081(RELEASE): 0x702015000100051:Wed Nov 18 11:20:20 GMT 2015    root@sea-build7-02:/b/mnt/obj/b/mnt/src/sys/IQ.amd64.release   clang version 3.3 (tags/RELEASE_33/final) amd64

**Comment by cbrainerd** [comment]
Please run `make tags` then try running `./build_stat_browser.py --cluster isilon.higkoo.com` again.

The step `make tags` should probably be added to [README-dev.md](https://github.com/Isilon/isilon_stat_browser/blob/master/README-dev.md)
